export enum EnumLoginReducer {
    SET_USERNAME = 'SET_USERNAME',
    SET_PASSWORD = 'SET_PASSWORD',
    TOGGLE_SECURE_TEXT_ENTRY = 'TOGGLE_SECURE_TEXT_ENTRY',
    VALIDATE_USERNAME = 'VALIDATE_USERNAME',
    VALIDATE_PASSWORD = 'VALIDATE_PASSWORD',
    SHOW_ERROR = 'SHOW_ERROR',
    RESET = 'RESET'
}